### ISSUE TITLE
fedora 40 flatpak goldendict-ng can't start.

### ISSUE THREAD

**Issue by dc-me** [xiaoyifang/goldendict-ng#1528]
**Describe the bug**

goldendict: symbol lookup error: goldendict: undefined symbol: _ZN10QAudioSink12stateChangedEN7QtAudio5StateE, version Qt_6

**To Reproduce**

flatpak run io.github.xiaoyifang.goldendict_ng

**Affected Dictionaries**

**Expected behavior**
Start as expected.

**Screenshots**

**OS and software versions**

NAME="Fedora Linux"
VERSION="40 (Workstation Edition)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation

**Additional context**

**Comment by shenlebantongying** [comment]
It's a known problem.

https://aur.archlinux.org/packages/goldendict-ng#comment-968163
https://bugreports.qt.io/browse/QTBUG-123997

It is supposed to be fixed in Qt6.7.1.

I am not sure how Flatpak updates runtime, but simply updating `org.kde.Platform` should fix the problem. The runtime is updated yesterday.

https://github.com/KDE/flatpak-kde-runtime/commit/1c7c27acc57d69ac549c6c10f285631208a6ea48

**Comment by dc-me** [comment]
flatpak list

KDE Application Platform                 org.kde.Platform                                                    5.15-23.08    flathub   system
KDE Application Platform                 org.kde.Platform                                                    6.7           flathub   system

It's already the latest version, reinstall ?

**Comment by shenlebantongying** [comment]
No idea, I cannot access my Linux machine right now 😅 

Maybe yes? 6.7 is just the "major version" and the runtime updates many times in the 6.7 branch -> https://github.com/KDE/flatpak-kde-runtime/tree/qt6.7

There should be someway to update it.

**Comment by dc-me** [comment]
I't running the latest builds with the commit that you mentioned.

KDE Application Platform - Shared libraries used by KDE applications

          ID: org.kde.Platform
         Ref: runtime/org.kde.Platform/x86_64/6.7
        Arch: x86_64
      Branch: 6.7
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 903.9 MB

      Commit: 638ad3a9882b4f9bd511373986860f722a9b1bc22fad0bd3dcdcb35a03f1dd2f
      Parent: d0bca68b8d2c7610794b2c517107540ff6188d867c00946359a3f88fcf1e7bbc
     Subject: build of org.kde.Sdk, Tue May 21 18:01:50 UTC 2024 (f5fd3cedc903634cb86f251af8590049ad86dd8d)
        Date: 2024-05-22 02:46:38 +0000


However it still not works.

**Comment by shenlebantongying** [comment]
It should be fixed after rebuild.

Note that FlatHub needs minutes to hours for publishing the new version.

**Comment by dc-me** [comment]
![image](https://github.com/xiaoyifang/goldendict-ng/assets/8910772/3a3fd5b3-75f8-40e6-b2e3-1d41e7b587df)

With the previous builds  in the test branch it works, but is not push to flathub. Why with the rebuild, can't push the previou build to flathub?

**Comment by shenlebantongying** [comment]
My change to README.md triggers a build, and it has `flathub_official_build=true` and the correct revision. 

https://buildbot.flathub.org/#/buildrequests/494109

It is currently not being built :sweat_smile: 

The build is usually fast, but today it seems some big projects are congesting the build queue. You can see the status here -> https://buildbot.flathub.org/#/

Probably need a day for it to be published, sadly.

**Comment by dc-me** [comment]
I don't think it's fixed, the image I showed earlier was from test branch, if I install from flathub, it still not working.

flatpak remote-info flathub io.github.xiaoyifang.goldendict_ng

```
ID: io.github.xiaoyifang.goldendict_ng
       Ref: app/io.github.xiaoyifang.goldendict_ng/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 24.05.05
   License: GPL-3.0-or-later
Collection: org.flathub.Stable
  Download: 125.7 MB
 Installed: 290.0 MB
   Runtime: org.kde.Platform/x86_64/6.7
       Sdk: org.kde.Sdk/x86_64/6.7

    Commit: 63aa4de461b8d61a8881758052a0ed005efffcc4f7c6eb1973921389ccfd4811
    Parent: eed686eb3647f5a18b47b9033c4ab49dce92935357445ce3f76e90593ad22551
   Subject: Update 2 modules (#26) (9a827ab4)
      Date: 2024-05-05 14:57:17 +0000
```
as you can see the Date is still 2024-05-05 , maybe you need to update the version for it to be updated in flathub.

**Comment by shenlebantongying** [comment]
My above reply means that we need to wait for the new build to be published.

There is nothing I can / need to do anymore. Just wait.

It is being built right now, and it will stay in the publishing queue for some time

https://buildbot.flathub.org/#/buildrequests/494109

Monitor https://buildbot.flathub.org/#/ if you want it ASAP.
